### PR TITLE
Minor updates for requirements

### PR DESCRIPTION
**Pull request by JulioPDX**
Updating AVD, CVP, and ansible-core versions

### CODE REVIEW

**Review by mthiel117 — COMMENTED** [review]
Do want to make this AVD 4.5 now?

**Comment by mthiel117** [comment]
We should also update the Lab guide's instructions (separate PR) to run the following commands.
```
pip3 config set global.disable-pip-version-check true
pip3 install -r requirements.txt
ansible-galaxy collection install -r requirements.yml
export ARISTA_AVD_DIR=$(ansible-galaxy collection list arista.avd --format yaml | head -1 | cut -d: -f1)
pip3 install -r ${ARISTA_AVD_DIR}/arista/avd/requirements.txt
```

to become:
```
pip3 config set global.disable-pip-version-check true
pip3 install -r requirements.txt
ansible-galaxy collection install -r requirements.yml
```

**Comment by mthiel117** [comment]
Successful test in ATD Lab with AVD 4.5 and CVP 3.10.1.

All AVD Labs run as desired.

**Comment by JulioPDX** [comment]
> We should also update the Lab guide's instructions (separate PR) to run the following commands.
> 
> ```
> pip3 config set global.disable-pip-version-check true
> pip3 install "ansible-core<2.15.0"
> ansible-galaxy collection install -r requirements.yml
> export ARISTA_AVD_DIR=$(ansible-galaxy collection list arista.avd --format yaml | head -1 | cut -d: -f1)
> pip3 install -r ${ARISTA_AVD_DIR}/arista/avd/requirements.txt
> ```
> 
> to become:
> 
> ```
> pip3 config set global.disable-pip-version-check true
> pip3 install -r requirements.txt
> ansible-galaxy collection install -r requirements.yml
> ```

The reason I keep it like this is to ensure we always have the correct python packages installed vs maintaining a separate requirments.txt file. We only need this file for the CICD workflow to install ansible-core

**Review by mthiel117 — APPROVED** [review]
LGTM

**Pull request merged**
